---
Name: shortcodable
After:
    - framework/*
    # - cms/*
---

LeftAndMain:
  extra_requirements_javascript:
    - 'resources/shortcodable/javascript/editor_plugin.js'
    - 'resources/shortcodable/javascript/shortcodable.js'
  extra_requirements_css:
    - 'shortcodable/css/shortcodable.css'

SilverStripe\Control\Director:
  rules:
    'admin/shortcodable': Silverstripe\Shortcodable\Controller\ShortcodableController

Shortcodable:
  htmleditor_names:
    - cms

HtmlEditorField:
  extensions:
    - ShortcodableHtmlEditorField

ShortcodeParser:
  extensions:
    - ShortcodableShortcodeParserExtension
